resource "local_file" "inventory" {
  content = <<-DOC
    # Ansible inventory containing variable values from Terraform.
    # Generated by Terraform.
   
revers ansible_host=${yandex_compute_instance.revers.network_interface.0.nat_ip_address} ansible_ssh_extra_args='-o StrictHostKeyChecking=no' ansible_ssh_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa
db01 ansible_host=${yandex_compute_instance.db01.network_interface.0.ip_address} ansible_ssh_extra_args='-o StrictHostKeyChecking=no' ansible_ssh_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -q ubuntu@${yandex_compute_instance.revers.network_interface.0.nat_ip_address}"'
db02 ansible_host=${yandex_compute_instance.db02.network_interface.0.ip_address} ansible_ssh_extra_args='-o StrictHostKeyChecking=no' ansible_ssh_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -q ubuntu@${yandex_compute_instance.revers.network_interface.0.nat_ip_address}"'
app ansible_host=${yandex_compute_instance.app.network_interface.0.ip_address} ansible_ssh_extra_args='-o StrictHostKeyChecking=no' ansible_ssh_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -q ubuntu@${yandex_compute_instance.revers.network_interface.0.nat_ip_address}"'
gitlab ansible_host=${yandex_compute_instance.gitlab.network_interface.0.ip_address} ansible_ssh_extra_args='-o StrictHostKeyChecking=no' ansible_ssh_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -q ubuntu@${yandex_compute_instance.revers.network_interface.0.nat_ip_address}"'
runner ansible_host=${yandex_compute_instance.runner.network_interface.0.ip_address} ansible_ssh_extra_args='-o StrictHostKeyChecking=no' ansible_ssh_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -q ubuntu@${yandex_compute_instance.revers.network_interface.0.nat_ip_address}"'
monitoring ansible_host=${yandex_compute_instance.monitoring.network_interface.0.ip_address} ansible_ssh_extra_args='-o StrictHostKeyChecking=no' ansible_ssh_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -q ubuntu@${yandex_compute_instance.revers.network_interface.0.nat_ip_address}"'
    
    DOC
  filename = "../ansible/inventory"

  depends_on = [
    yandex_compute_instance.revers,
    yandex_compute_instance.db01,
    yandex_compute_instance.db02,
    yandex_compute_instance.app,
    yandex_compute_instance.gitlab,
    yandex_compute_instance.runner,
    yandex_compute_instance.monitoring
  ]
}
